<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "typoscriptconditions"
 *
 * Auto generated by Extension Builder 2016-06-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TypoScript Conditions',
	'description' => 'collection of useful TypoScript conditions',
	'category' => 'misc',
	'author' => 'Franz Kugelmann',
	'author_email' => 'franz.kugelmann@elementare-teilchen.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);